### ISSUE TITLE
How to create wheels

### ISSUE THREAD

**Issue by rvanlaar** [WyattBlue/pyav#9]
Please consider adding this to the documentation.

For others, who weren't able to build good wheels because of:

    ImportError: libavdevice.so.60: cannot open shared object file: No such file or directory

Standard wheel is missing the vendorized ffmpeg. To fix this issue:
```
    pip install auditwheel
    sudo apt install patchelf

    LD_LIBRARY_PATH=.vendor/build/ffmpeg-6.0:$LD_LIBRARY_PATH auditwheel repair --plat linux_x86_64 -w output-dir dist/*whl
```

This creates a wheel in `output-dir`.

**Comment by WyattBlue** [comment]
I've updated the readme to better reflect how I test my local pyav. But I don't think we need to document how to build wheels for Ubuntu specifically (The github workflow kindof already documents this). Ideally, you would also get all ffmpeg libraries from `./build-deps` instead of relying on the usually out of date distro libs.
